import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import convert1
import ceasar
import sub
import vigenere
import hashing
import rsa_utils
import aes

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 514)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setWindowIcon(QtGui.QIcon('.\ITPTIT-01.png'))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.general = QtWidgets.QTabWidget(self.centralwidget)
        self.general.setGeometry(QtCore.QRect(0, 0, 711, 481))
        self.general.setObjectName("general")
        self.convert = QtWidgets.QWidget()
        self.convert.setObjectName("convert")
        self.rsButton = QtWidgets.QPushButton(self.convert)
        self.rsButton.setGeometry(QtCore.QRect(170, 370, 151, 71))
        self.rsButton.setObjectName("rsButton")
        self.convertButton_conv = QtWidgets.QPushButton(self.convert)
        self.convertButton_conv.setGeometry(QtCore.QRect(490, 370, 151, 71))
        self.convertButton_conv.setObjectName("convertButton_conv")
        self.asciiBox = QtWidgets.QLineEdit(self.convert)
        self.asciiBox.setGeometry(QtCore.QRect(330, 70, 361, 20))
        self.asciiBox.setObjectName("asciiBox")
        self.decBox = QtWidgets.QLineEdit(self.convert)
        self.decBox.setGeometry(QtCore.QRect(330, 110, 361, 20))
        self.decBox.setObjectName("decBox")
        self.binBox = QtWidgets.QLineEdit(self.convert)
        self.binBox.setGeometry(QtCore.QRect(330, 150, 361, 20))
        self.binBox.setObjectName("binBox")
        self.hexBox = QtWidgets.QLineEdit(self.convert)
        self.hexBox.setGeometry(QtCore.QRect(330, 190, 361, 20))
        self.hexBox.setObjectName("hexBox")
        self.octBox = QtWidgets.QLineEdit(self.convert)
        self.octBox.setGeometry(QtCore.QRect(330, 230, 361, 20))
        self.octBox.setObjectName("octBox")
        self.b64Box = QtWidgets.QLineEdit(self.convert)
        self.b64Box.setGeometry(QtCore.QRect(330, 270, 361, 20))
        self.b64Box.setObjectName("b64Box")
        self.label = QtWidgets.QLabel(self.convert)
        self.label.setGeometry(QtCore.QRect(290, 70, 41, 21))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.convert)
        self.label_2.setGeometry(QtCore.QRect(280, 110, 47, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.convert)
        self.label_3.setGeometry(QtCore.QRect(260, 190, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.convert)
        self.label_4.setGeometry(QtCore.QRect(280, 150, 41, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.convert)
        self.label_5.setGeometry(QtCore.QRect(290, 230, 31, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.convert)
        self.label_6.setGeometry(QtCore.QRect(280, 270, 47, 16))
        self.label_6.setObjectName("label_6")
        self.image = QtWidgets.QLabel(self.convert)
        self.image.setGeometry(QtCore.QRect(30, 80, 211, 211))
        self.image.setStyleSheet("image: url(:/newPrefix/ITPTIT-01.png)")
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("ITPTIT-01.png"))
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.general.addTab(self.convert, "")
        self.crypto = QtWidgets.QWidget()
        self.crypto.setObjectName("crypto")
        self.tabWidget = QtWidgets.QTabWidget(self.crypto)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 711, 461))
        self.tabWidget.setObjectName("tabWidget")
        self.ceasar = QtWidgets.QWidget()
        self.ceasar.setObjectName("ceasar")
        self.line = QtWidgets.QFrame(self.ceasar)
        self.line.setGeometry(QtCore.QRect(350, -30, 20, 471))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.ci_de_cea = QtWidgets.QPlainTextEdit(self.ceasar)
        self.ci_de_cea.setGeometry(QtCore.QRect(60, 100, 281, 91))
        self.ci_de_cea.setObjectName("ci_de_cea")
        self.label_8 = QtWidgets.QLabel(self.ceasar)
        self.label_8.setGeometry(QtCore.QRect(10, 80, 91, 21))
        self.label_8.setObjectName("label_8")
        self.spin_de_cea = QtWidgets.QSpinBox(self.ceasar)
        self.spin_de_cea.setGeometry(QtCore.QRect(60, 210, 51, 22))
        self.spin_de_cea.setMaximum(27)
        self.spin_de_cea.setObjectName("spin_de_cea")
        self.label_9 = QtWidgets.QLabel(self.ceasar)
        self.label_9.setGeometry(QtCore.QRect(80, 0, 211, 71))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.ceasar)
        self.label_10.setGeometry(QtCore.QRect(10, 210, 41, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.ceasar)
        self.label_11.setGeometry(QtCore.QRect(10, 290, 81, 16))
        self.label_11.setObjectName("label_11")
        self.pl_de_cea = QtWidgets.QPlainTextEdit(self.ceasar)
        self.pl_de_cea.setGeometry(QtCore.QRect(60, 320, 281, 91))
        self.pl_de_cea.setReadOnly(True)
        self.pl_de_cea.setObjectName("pl_de_cea")
        self.bt_de_cea = QtWidgets.QPushButton(self.ceasar)
        self.bt_de_cea.setGeometry(QtCore.QRect(140, 250, 91, 31))
        self.bt_de_cea.setObjectName("bt_de_cea")
        self.label_12 = QtWidgets.QLabel(self.ceasar)
        self.label_12.setGeometry(QtCore.QRect(440, 0, 221, 71))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.ceasar)
        self.label_13.setGeometry(QtCore.QRect(370, 80, 91, 21))
        self.label_13.setObjectName("label_13")
        self.pl_en_cea = QtWidgets.QPlainTextEdit(self.ceasar)
        self.pl_en_cea.setGeometry(QtCore.QRect(410, 100, 281, 91))
        self.pl_en_cea.setObjectName("pl_en_cea")
        self.label_14 = QtWidgets.QLabel(self.ceasar)
        self.label_14.setGeometry(QtCore.QRect(370, 210, 41, 16))
        self.label_14.setObjectName("label_14")
        self.spin_en_cea = QtWidgets.QSpinBox(self.ceasar)
        self.spin_en_cea.setGeometry(QtCore.QRect(420, 210, 51, 22))
        self.spin_en_cea.setMaximum(27)
        self.spin_en_cea.setObjectName("spin_en_cea")
        self.bt_en_cea = QtWidgets.QPushButton(self.ceasar)
        self.bt_en_cea.setGeometry(QtCore.QRect(510, 250, 91, 31))
        self.bt_en_cea.setObjectName("bt_en_cea")
        self.label_15 = QtWidgets.QLabel(self.ceasar)
        self.label_15.setGeometry(QtCore.QRect(370, 290, 91, 21))
        self.label_15.setObjectName("label_15")
        self.ci_en_cea = QtWidgets.QPlainTextEdit(self.ceasar)
        self.ci_en_cea.setGeometry(QtCore.QRect(410, 320, 281, 91))
        self.ci_en_cea.setReadOnly(True)
        self.ci_en_cea.setObjectName("ci_en_cea")
        self.tabWidget.addTab(self.ceasar, "")
        self.sub = QtWidgets.QWidget()
        self.sub.setObjectName("sub")
        self.line_2 = QtWidgets.QFrame(self.sub)
        self.line_2.setGeometry(QtCore.QRect(350, -10, 20, 471))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_16 = QtWidgets.QLabel(self.sub)
        self.label_16.setGeometry(QtCore.QRect(10, 290, 81, 16))
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.sub)
        self.label_18.setGeometry(QtCore.QRect(370, 290, 91, 21))
        self.label_18.setObjectName("label_18")
        self.pl_de_sub = QtWidgets.QPlainTextEdit(self.sub)
        self.pl_de_sub.setGeometry(QtCore.QRect(60, 320, 281, 91))
        self.pl_de_sub.setReadOnly(True)
        self.pl_de_sub.setObjectName("pl_de_sub")
        self.bt_de_sub = QtWidgets.QPushButton(self.sub)
        self.bt_de_sub.setGeometry(QtCore.QRect(140, 260, 91, 31))
        self.bt_de_sub.setObjectName("bt_de_sub")
        self.line_3 = QtWidgets.QFrame(self.sub)
        self.line_3.setGeometry(QtCore.QRect(350, -30, 20, 471))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_19 = QtWidgets.QLabel(self.sub)
        self.label_19.setGeometry(QtCore.QRect(80, 0, 211, 71))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.sub)
        self.label_20.setGeometry(QtCore.QRect(440, 0, 221, 71))
        self.label_20.setObjectName("label_20")
        self.pl_en_sub = QtWidgets.QPlainTextEdit(self.sub)
        self.pl_en_sub.setGeometry(QtCore.QRect(410, 100, 281, 91))
        self.pl_en_sub.setObjectName("pl_en_sub")
        self.label_21 = QtWidgets.QLabel(self.sub)
        self.label_21.setGeometry(QtCore.QRect(0, 200, 161, 21))
        self.label_21.setObjectName("label_21")
        self.bt_en_sub = QtWidgets.QPushButton(self.sub)
        self.bt_en_sub.setGeometry(QtCore.QRect(510, 260, 91, 31))
        self.bt_en_sub.setObjectName("bt_en_sub")
        self.ci_en_sub = QtWidgets.QPlainTextEdit(self.sub)
        self.ci_en_sub.setGeometry(QtCore.QRect(410, 320, 281, 91))
        self.ci_en_sub.setReadOnly(True)
        self.ci_en_sub.setObjectName("ci_en_sub")
        self.label_22 = QtWidgets.QLabel(self.sub)
        self.label_22.setGeometry(QtCore.QRect(370, 80, 91, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.sub)
        self.label_23.setGeometry(QtCore.QRect(10, 80, 91, 21))
        self.label_23.setObjectName("label_23")
        self.ci_de_sub = QtWidgets.QPlainTextEdit(self.sub)
        self.ci_de_sub.setGeometry(QtCore.QRect(60, 100, 281, 91))
        self.ci_de_sub.setObjectName("ci_de_sub")
        self.label_24 = QtWidgets.QLabel(self.sub)
        self.label_24.setGeometry(QtCore.QRect(370, 200, 161, 21))
        self.label_24.setObjectName("label_24")
        self.key_de_sub = QtWidgets.QLineEdit(self.sub)
        self.key_de_sub.setGeometry(QtCore.QRect(20, 230, 281, 20))
        self.key_de_sub.setObjectName("key_de_sub")
        self.key_en_sub = QtWidgets.QLineEdit(self.sub)
        self.key_en_sub.setGeometry(QtCore.QRect(390, 230, 281, 20))
        self.key_en_sub.setObjectName("key_en_sub")
        self.tabWidget.addTab(self.sub, "")
        self.vig = QtWidgets.QWidget()
        self.vig.setObjectName("vig")
        self.ci_en_vig = QtWidgets.QPlainTextEdit(self.vig)
        self.ci_en_vig.setGeometry(QtCore.QRect(410, 320, 281, 91))
        self.ci_en_vig.setReadOnly(True)
        self.ci_en_vig.setObjectName("ci_en_vig")
        self.pl_en_vig = QtWidgets.QPlainTextEdit(self.vig)
        self.pl_en_vig.setGeometry(QtCore.QRect(410, 100, 281, 91))
        self.pl_en_vig.setObjectName("pl_en_vig")
        self.bt_en_vig = QtWidgets.QPushButton(self.vig)
        self.bt_en_vig.setGeometry(QtCore.QRect(510, 260, 91, 31))
        self.bt_en_vig.setObjectName("bt_en_vig")
        self.label_25 = QtWidgets.QLabel(self.vig)
        self.label_25.setGeometry(QtCore.QRect(10, 80, 91, 21))
        self.label_25.setObjectName("label_25")
        self.ci_de_vig = QtWidgets.QPlainTextEdit(self.vig)
        self.ci_de_vig.setGeometry(QtCore.QRect(60, 100, 281, 91))
        self.ci_de_vig.setObjectName("ci_de_vig")
        self.label_26 = QtWidgets.QLabel(self.vig)
        self.label_26.setGeometry(QtCore.QRect(80, 0, 211, 71))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.vig)
        self.label_27.setGeometry(QtCore.QRect(370, 80, 91, 21))
        self.label_27.setObjectName("label_27")
        self.line_4 = QtWidgets.QFrame(self.vig)
        self.line_4.setGeometry(QtCore.QRect(350, -30, 20, 471))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.bt_de_vig = QtWidgets.QPushButton(self.vig)
        self.bt_de_vig.setGeometry(QtCore.QRect(140, 260, 91, 31))
        self.bt_de_vig.setObjectName("bt_de_vig")
        self.pl_de_vig = QtWidgets.QPlainTextEdit(self.vig)
        self.pl_de_vig.setEnabled(True)
        self.pl_de_vig.setGeometry(QtCore.QRect(60, 320, 281, 91))
        self.pl_de_vig.setReadOnly(True)
        self.pl_de_vig.setObjectName("pl_de_vig")
        self.key_de_vig = QtWidgets.QLineEdit(self.vig)
        self.key_de_vig.setGeometry(QtCore.QRect(20, 230, 281, 20))
        self.key_de_vig.setObjectName("key_de_vig")
        self.label_28 = QtWidgets.QLabel(self.vig)
        self.label_28.setGeometry(QtCore.QRect(380, 200, 41, 21))
        self.label_28.setObjectName("label_28")
        self.label_17 = QtWidgets.QLabel(self.vig)
        self.label_17.setGeometry(QtCore.QRect(10, 290, 81, 16))
        self.label_17.setObjectName("label_17")
        self.label_29 = QtWidgets.QLabel(self.vig)
        self.label_29.setGeometry(QtCore.QRect(10, 200, 31, 21))
        self.label_29.setObjectName("label_29")
        self.key_en_vig = QtWidgets.QLineEdit(self.vig)
        self.key_en_vig.setGeometry(QtCore.QRect(390, 230, 281, 20))
        self.key_en_vig.setObjectName("key_en_vig")
        self.label_30 = QtWidgets.QLabel(self.vig)
        self.label_30.setGeometry(QtCore.QRect(440, 0, 211, 71))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.vig)
        self.label_31.setGeometry(QtCore.QRect(370, 290, 91, 21))
        self.label_31.setObjectName("label_31")
        self.tabWidget.addTab(self.vig, "")
        self.general.addTab(self.crypto, "")
        self.hashing = QtWidgets.QWidget()
        self.hashing.setObjectName("hashing")
        self.sha256Box = QtWidgets.QLineEdit(self.hashing)
        self.sha256Box.setGeometry(QtCore.QRect(330, 230, 361, 20))
        self.sha256Box.setReadOnly(True)
        self.sha256Box.setObjectName("sha256Box")
        self.ripBox = QtWidgets.QLineEdit(self.hashing)
        self.ripBox.setGeometry(QtCore.QRect(330, 150, 361, 20))
        self.ripBox.setReadOnly(True)
        self.ripBox.setObjectName("ripBox")
        self.sha512Box = QtWidgets.QLineEdit(self.hashing)
        self.sha512Box.setGeometry(QtCore.QRect(330, 270, 361, 20))
        self.sha512Box.setReadOnly(True)
        self.sha512Box.setObjectName("sha512Box")
        self.label_7 = QtWidgets.QLabel(self.hashing)
        self.label_7.setGeometry(QtCore.QRect(290, 70, 41, 21))
        self.label_7.setScaledContents(False)
        self.label_7.setObjectName("label_7")
        self.asciiBox_hash = QtWidgets.QLineEdit(self.hashing)
        self.asciiBox_hash.setGeometry(QtCore.QRect(330, 70, 361, 20))
        self.asciiBox_hash.setObjectName("asciiBox_hash")
        self.label_32 = QtWidgets.QLabel(self.hashing)
        self.label_32.setGeometry(QtCore.QRect(280, 230, 51, 21))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.hashing)
        self.label_33.setGeometry(QtCore.QRect(290, 110, 31, 21))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.hashing)
        self.label_34.setGeometry(QtCore.QRect(290, 190, 31, 21))
        self.label_34.setObjectName("label_34")
        self.sha1Box = QtWidgets.QLineEdit(self.hashing)
        self.sha1Box.setGeometry(QtCore.QRect(330, 190, 361, 20))
        self.sha1Box.setReadOnly(True)
        self.sha1Box.setObjectName("sha1Box")
        self.md5Box = QtWidgets.QLineEdit(self.hashing)
        self.md5Box.setGeometry(QtCore.QRect(330, 110, 361, 20))
        self.md5Box.setReadOnly(True)
        self.md5Box.setObjectName("md5Box")
        self.label_35 = QtWidgets.QLabel(self.hashing)
        self.label_35.setGeometry(QtCore.QRect(260, 150, 61, 20))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.hashing)
        self.label_36.setGeometry(QtCore.QRect(280, 270, 51, 21))
        self.label_36.setObjectName("label_36")
        self.image_2 = QtWidgets.QLabel(self.hashing)
        self.image_2.setGeometry(QtCore.QRect(30, 80, 211, 211))
        self.image_2.setStyleSheet("image: url(:/newPrefix/ITPTIT-01.png)")
        self.image_2.setText("")
        self.image_2.setPixmap(QtGui.QPixmap("ITPTIT-01.png"))
        self.image_2.setScaledContents(True)
        self.image_2.setObjectName("image_2")
        self.label_37 = QtWidgets.QLabel(self.hashing)
        self.label_37.setGeometry(QtCore.QRect(270, 310, 51, 21))
        self.label_37.setObjectName("label_37")
        self.sha3Box = QtWidgets.QLineEdit(self.hashing)
        self.sha3Box.setGeometry(QtCore.QRect(330, 310, 361, 20))
        self.sha3Box.setReadOnly(True)
        self.sha3Box.setObjectName("sha3Box")
        self.crc32Box = QtWidgets.QLineEdit(self.hashing)
        self.crc32Box.setGeometry(QtCore.QRect(330, 350, 361, 20))
        self.crc32Box.setReadOnly(True)
        self.crc32Box.setObjectName("crc32Box")
        self.label_38 = QtWidgets.QLabel(self.hashing)
        self.label_38.setGeometry(QtCore.QRect(280, 350, 41, 21))
        self.label_38.setObjectName("label_38")
        self.convertButton_hash = QtWidgets.QPushButton(self.hashing)
        self.convertButton_hash.setGeometry(QtCore.QRect(60, 330, 151, 71))
        self.convertButton_hash.setObjectName("convertButton_hash")
        self.general.addTab(self.hashing, "")
        self.decrypt = QtWidgets.QWidget()
        self.decrypt.setObjectName("decrypt")
        self.decrypt_2 = QtWidgets.QTabWidget(self.decrypt)
        self.decrypt_2.setGeometry(QtCore.QRect(0, 0, 711, 451))
        self.decrypt_2.setObjectName("decrypt_2")
        self.rsa = QtWidgets.QWidget()
        self.rsa.setObjectName("rsa")
        self.label_39 = QtWidgets.QLabel(self.rsa)
        self.label_39.setGeometry(QtCore.QRect(240, 0, 201, 31))
        self.label_39.setObjectName("label_39")
        self.line_5 = QtWidgets.QFrame(self.rsa)
        self.line_5.setGeometry(QtCore.QRect(340, 120, 20, 471))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.rsa)
        self.line_6.setGeometry(QtCore.QRect(-20, 110, 751, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_40 = QtWidgets.QLabel(self.rsa)
        self.label_40.setGeometry(QtCore.QRect(0, 40, 91, 21))
        self.label_40.setObjectName("label_40")
        self.RSAKeySize_gen = QtWidgets.QComboBox(self.rsa)
        self.RSAKeySize_gen.setGeometry(QtCore.QRect(100, 40, 69, 22))
        self.RSAKeySize_gen.setObjectName("RSAKeySize_gen")
        self.RSAKeySize_gen.addItem("")
        self.RSAKeySize_gen.addItem("")
        self.RSAKeySize_gen.addItem("")
        self.RSAKeySize_gen.addItem("")
        self.label_41 = QtWidgets.QLabel(self.rsa)
        self.label_41.setGeometry(QtCore.QRect(190, 30, 71, 21))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.rsa)
        self.label_42.setGeometry(QtCore.QRect(450, 30, 81, 21))
        self.label_42.setObjectName("label_42")
        self.pubKey_gen = QtWidgets.QPlainTextEdit(self.rsa)
        self.pubKey_gen.setGeometry(QtCore.QRect(200, 50, 221, 41))
        self.pubKey_gen.setReadOnly(True)
        self.pubKey_gen.setObjectName("pubKey_gen")
        self.priKey_gen = QtWidgets.QPlainTextEdit(self.rsa)
        self.priKey_gen.setGeometry(QtCore.QRect(460, 50, 221, 41))
        self.priKey_gen.setReadOnly(True)
        self.priKey_gen.setObjectName("priKey_gen")
        self.bt_gen = QtWidgets.QPushButton(self.rsa)
        self.bt_gen.setGeometry(QtCore.QRect(40, 70, 81, 31))
        self.bt_gen.setObjectName("bt_gen")
        self.label_43 = QtWidgets.QLabel(self.rsa)
        self.label_43.setGeometry(QtCore.QRect(100, 130, 161, 31))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.rsa)
        self.label_44.setGeometry(QtCore.QRect(460, 130, 161, 31))
        self.label_44.setObjectName("label_44")
        self.plain_en = QtWidgets.QPlainTextEdit(self.rsa)
        self.plain_en.setGeometry(QtCore.QRect(20, 190, 321, 51))
        self.plain_en.setObjectName("plain_en")
        self.pubKey_en = QtWidgets.QPlainTextEdit(self.rsa)
        self.pubKey_en.setGeometry(QtCore.QRect(20, 280, 221, 41))
        self.pubKey_en.setObjectName("pubKey_en")
        self.label_45 = QtWidgets.QLabel(self.rsa)
        self.label_45.setGeometry(QtCore.QRect(10, 160, 81, 16))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.rsa)
        self.label_46.setGeometry(QtCore.QRect(10, 250, 81, 21))
        self.label_46.setObjectName("label_46")
        self.bt_en_rsa = QtWidgets.QPushButton(self.rsa)
        self.bt_en_rsa.setGeometry(QtCore.QRect(260, 280, 81, 41))
        self.bt_en_rsa.setObjectName("bt_en_rsa")
        self.label_47 = QtWidgets.QLabel(self.rsa)
        self.label_47.setGeometry(QtCore.QRect(10, 330, 111, 31))
        self.label_47.setObjectName("label_47")
        self.encrypt_en = QtWidgets.QPlainTextEdit(self.rsa)
        self.encrypt_en.setGeometry(QtCore.QRect(20, 360, 321, 51))
        self.encrypt_en.setReadOnly(True)
        self.encrypt_en.setObjectName("encrypt_en")
        self.priKey_de = QtWidgets.QPlainTextEdit(self.rsa)
        self.priKey_de.setGeometry(QtCore.QRect(370, 280, 221, 41))
        self.priKey_de.setObjectName("priKey_de")
        self.label_48 = QtWidgets.QLabel(self.rsa)
        self.label_48.setGeometry(QtCore.QRect(360, 160, 121, 31))
        self.label_48.setObjectName("label_48")
        self.encrypt_de = QtWidgets.QPlainTextEdit(self.rsa)
        self.encrypt_de.setGeometry(QtCore.QRect(370, 190, 321, 51))
        self.encrypt_de.setObjectName("encrypt_de")
        self.bt_de_rsa = QtWidgets.QPushButton(self.rsa)
        self.bt_de_rsa.setGeometry(QtCore.QRect(610, 280, 91, 41))
        self.bt_de_rsa.setObjectName("bt_de_rsa")
        self.label_49 = QtWidgets.QLabel(self.rsa)
        self.label_49.setGeometry(QtCore.QRect(360, 330, 91, 21))
        self.label_49.setObjectName("label_49")
        self.plain_de = QtWidgets.QPlainTextEdit(self.rsa)
        self.plain_de.setGeometry(QtCore.QRect(370, 360, 321, 51))
        self.plain_de.setReadOnly(True)
        self.plain_de.setObjectName("plain_de")
        self.label_50 = QtWidgets.QLabel(self.rsa)
        self.label_50.setGeometry(QtCore.QRect(360, 250, 91, 21))
        self.label_50.setObjectName("label_50")
        self.decrypt_2.addTab(self.rsa, "")
        self.aes = QtWidgets.QWidget()
        self.aes.setObjectName("aes")
        self.key_en_aes = QtWidgets.QLineEdit(self.aes)
        self.key_en_aes.setGeometry(QtCore.QRect(400, 240, 271, 21))
        self.key_en_aes.setObjectName("key_en_aes")
        self.label_51 = QtWidgets.QLabel(self.aes)
        self.label_51.setGeometry(QtCore.QRect(30, 0, 291, 71))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.aes)
        self.label_52.setGeometry(QtCore.QRect(10, 300, 121, 31))
        self.label_52.setObjectName("label_52")
        self.en_en_aes = QtWidgets.QPlainTextEdit(self.aes)
        self.en_en_aes.setGeometry(QtCore.QRect(400, 110, 271, 51))
        self.en_en_aes.setObjectName("en_en_aes")
        self.label_53 = QtWidgets.QLabel(self.aes)
        self.label_53.setGeometry(QtCore.QRect(10, 210, 31, 21))
        self.label_53.setObjectName("label_53")
        self.pl_en_aes = QtWidgets.QPlainTextEdit(self.aes)
        self.pl_en_aes.setGeometry(QtCore.QRect(400, 340, 271, 71))
        self.pl_en_aes.setReadOnly(True)
        self.pl_en_aes.setObjectName("pl_en_aes")
        self.pl_de_aes = QtWidgets.QPlainTextEdit(self.aes)
        self.pl_de_aes.setGeometry(QtCore.QRect(50, 110, 271, 51))
        self.pl_de_aes.setObjectName("pl_de_aes")
        self.label_54 = QtWidgets.QLabel(self.aes)
        self.label_54.setGeometry(QtCore.QRect(10, 70, 91, 21))
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.aes)
        self.label_55.setGeometry(QtCore.QRect(400, 0, 281, 71))
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.aes)
        self.label_56.setGeometry(QtCore.QRect(370, 210, 41, 21))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.aes)
        self.label_57.setGeometry(QtCore.QRect(370, 70, 121, 21))
        self.label_57.setObjectName("label_57")
        self.bt_de_aes = QtWidgets.QPushButton(self.aes)
        self.bt_de_aes.setGeometry(QtCore.QRect(140, 270, 91, 31))
        self.bt_de_aes.setObjectName("bt_de_aes")
        self.en_de_aes = QtWidgets.QPlainTextEdit(self.aes)
        self.en_de_aes.setGeometry(QtCore.QRect(50, 340, 271, 71))
        self.en_de_aes.setReadOnly(True)
        self.en_de_aes.setObjectName("en_de_aes")
        self.bt_en_aes = QtWidgets.QPushButton(self.aes)
        self.bt_en_aes.setGeometry(QtCore.QRect(510, 270, 91, 31))
        self.bt_en_aes.setObjectName("bt_en_aes")
        self.label_58 = QtWidgets.QLabel(self.aes)
        self.label_58.setGeometry(QtCore.QRect(370, 300, 91, 21))
        self.label_58.setObjectName("label_58")
        self.key_de_aes = QtWidgets.QLineEdit(self.aes)
        self.key_de_aes.setGeometry(QtCore.QRect(50, 240, 271, 21))
        self.key_de_aes.setObjectName("key_de_aes")
        self.line_7 = QtWidgets.QFrame(self.aes)
        self.line_7.setGeometry(QtCore.QRect(340, -30, 20, 471))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.keySize_de = QtWidgets.QComboBox(self.aes)
        self.keySize_de.setGeometry(QtCore.QRect(80, 180, 69, 22))
        self.keySize_de.setObjectName("keySize_de")
        self.keySize_de.addItem("")
        self.keySize_de.addItem("")
        self.keySize_de.addItem("")
        self.mode_de = QtWidgets.QComboBox(self.aes)
        self.mode_de.setGeometry(QtCore.QRect(230, 180, 69, 22))
        self.mode_de.setObjectName("mode_de")
        self.mode_de.addItem("")
        self.mode_de.addItem("")
        self.label_59 = QtWidgets.QLabel(self.aes)
        self.label_59.setGeometry(QtCore.QRect(10, 180, 71, 21))
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.aes)
        self.label_60.setGeometry(QtCore.QRect(180, 180, 51, 21))
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.aes)
        self.label_61.setGeometry(QtCore.QRect(540, 180, 51, 21))
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.aes)
        self.label_62.setGeometry(QtCore.QRect(370, 180, 71, 21))
        self.label_62.setObjectName("label_62")
        self.mode_en = QtWidgets.QComboBox(self.aes)
        self.mode_en.setGeometry(QtCore.QRect(590, 180, 69, 22))
        self.mode_en.setObjectName("mode_en")
        self.mode_en.addItem("")
        self.mode_en.addItem("")
        self.keySize_en = QtWidgets.QComboBox(self.aes)
        self.keySize_en.setGeometry(QtCore.QRect(440, 180, 69, 22))
        self.keySize_en.setObjectName("keySize_en")
        self.keySize_en.addItem("")
        self.keySize_en.addItem("")
        self.keySize_en.addItem("")
        self.decrypt_2.addTab(self.aes, "")
        self.general.addTab(self.decrypt, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit_Alt_F4 = QtWidgets.QAction(MainWindow)
        self.actionExit_Alt_F4.setObjectName("actionExit_Alt_F4")

        self.retranslateUi(MainWindow)
        self.general.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.decrypt_2.setCurrentIndex(0)
        self.RSAKeySize_gen.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Convert Tools"))
        self.rsButton.setText(_translate("MainWindow", "Reset"))
        self.convertButton_conv.setText(_translate("MainWindow", "Convert"))
        self.label.setText(_translate("MainWindow", "ASCII:"))
        self.label_2.setText(_translate("MainWindow", "Decimal:"))
        self.label_3.setText(_translate("MainWindow", "Hexadecimal:"))
        self.label_4.setText(_translate("MainWindow", "Binary:"))
        self.label_5.setText(_translate("MainWindow", "Octal:"))
        self.label_6.setText(_translate("MainWindow", "Base64:"))
        self.general.setTabText(self.general.indexOf(self.convert), _translate("MainWindow", "General Convert"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Cipher Text:</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; color:#00ff00;\">DECODER</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Shift:</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Plain Text:</span></p></body></html>"))
        self.bt_de_cea.setText(_translate("MainWindow", "Decode!"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; color:#ff0000;\">ENCODER</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Plain Text:</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Shift:</span></p></body></html>"))
        self.bt_en_cea.setText(_translate("MainWindow", "Encode!"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Cipher Text:</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ceasar), _translate("MainWindow", "Ceasar Cipher"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Plain Text:</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Cipher Text:</span></p></body></html>"))
        self.bt_de_sub.setText(_translate("MainWindow", "Decode!"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; color:#00ff00;\">DECODER</span></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; color:#ff0000;\">ENCODER</span></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">CipherText Alphabet:</span></p></body></html>"))
        self.bt_en_sub.setText(_translate("MainWindow", "Encode!"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Plain Text:</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Cipher Text:</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">CipherText Alphabet:</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sub), _translate("MainWindow", "Substitution Cipher"))
        self.bt_en_vig.setText(_translate("MainWindow", "Encode!"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Cipher Text:</span></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; color:#00ff00;\">DECODER</span></p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Plain Text:</span></p></body></html>"))
        self.bt_de_vig.setText(_translate("MainWindow", "Decode!"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Key:</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Plain Text:</span></p></body></html>"))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Key:</span></p></body></html>"))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; color:#ff0000;\">ENCODER</span></p></body></html>"))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Cipher Text:</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.vig), _translate("MainWindow", "Vigenère Cipher"))
        self.general.setTabText(self.general.indexOf(self.crypto), _translate("MainWindow", "Classical Crypto"))
        self.label_7.setText(_translate("MainWindow", "ASCII:"))
        self.label_32.setText(_translate("MainWindow", "SHA256:"))
        self.label_33.setText(_translate("MainWindow", "MD5:"))
        self.label_34.setText(_translate("MainWindow", "SHA1:"))
        self.label_35.setText(_translate("MainWindow", "RIPEMD160:"))
        self.label_36.setText(_translate("MainWindow", "SHA512:"))
        self.label_37.setText(_translate("MainWindow", "SHA3-512:"))
        self.label_38.setText(_translate("MainWindow", "CRC32:"))
        self.convertButton_hash.setText(_translate("MainWindow", "Convert"))
        self.general.setTabText(self.general.indexOf(self.hashing), _translate("MainWindow", "Hashing"))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; color:#5500ff;\">GENERATE KEYS</span></p></body></html>"))
        self.label_40.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#5555ff;\">RSA Key Size:</span></p></body></html>"))
        self.RSAKeySize_gen.setCurrentText(_translate("MainWindow", "1024"))
        self.RSAKeySize_gen.setItemText(0, _translate("MainWindow", "1024"))
        self.RSAKeySize_gen.setItemText(1, _translate("MainWindow", "2048"))
        self.RSAKeySize_gen.setItemText(2, _translate("MainWindow", "3072"))
        self.RSAKeySize_gen.setItemText(3, _translate("MainWindow", "4096"))
        self.label_41.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#5555ff;\">Public Key:</span></p></body></html>"))
        self.label_42.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#5555ff;\">Private key:</span></p></body></html>"))
        self.bt_gen.setText(_translate("MainWindow", "Generate!"))
        self.label_43.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; color:#5500ff;\">ENCRYPTION</span></p></body></html>"))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; color:#5500ff;\">DECRYPTION</span></p></body></html>"))
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Plain Text:</span></p></body></html>"))
        self.label_46.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Public Key:</span></p></body></html>"))
        self.bt_en_rsa.setText(_translate("MainWindow", "Encrypt!"))
        self.label_47.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Encrypted Text:</span></p></body></html>"))
        self.label_48.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Encrypted Text:</span></p></body></html>"))
        self.bt_de_rsa.setText(_translate("MainWindow", "Decrypt!"))
        self.label_49.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Plain Text:</span></p></body></html>"))
        self.label_50.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Private Key:</span></p></body></html>"))
        self.decrypt_2.setTabText(self.decrypt_2.indexOf(self.rsa), _translate("MainWindow", "RSA"))
        self.label_51.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; color:#00ff00;\">DECRYPTION</span></p></body></html>"))
        self.label_52.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Encrypted Text:</span></p></body></html>"))
        self.label_53.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Key:</span></p></body></html>"))
        self.label_54.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Plain Text:</span></p></body></html>"))
        self.label_55.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; color:#ff0000;\">ENCRYPTION</span></p></body></html>"))
        self.label_56.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Key:</span></p></body></html>"))
        self.label_57.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Encrypted Text:</span></p></body></html>"))
        self.bt_de_aes.setText(_translate("MainWindow", "Decrypt!"))
        self.bt_en_aes.setText(_translate("MainWindow", "Encrypt!"))
        self.label_58.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Plain Text:</span></p></body></html>"))
        self.keySize_de.setItemText(0, _translate("MainWindow", "128"))
        self.keySize_de.setItemText(1, _translate("MainWindow", "192"))
        self.keySize_de.setItemText(2, _translate("MainWindow", "256"))
        self.mode_de.setItemText(0, _translate("MainWindow", "ECB"))
        self.mode_de.setItemText(1, _translate("MainWindow", "CFB"))
        self.label_59.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Key Size:</span></p></body></html>"))
        self.label_60.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Mode:</span></p></body></html>"))
        self.label_61.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Mode:</span></p></body></html>"))
        self.label_62.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0055ff;\">Key Size:</span></p></body></html>"))
        self.mode_en.setItemText(0, _translate("MainWindow", "ECB"))
        self.mode_en.setItemText(1, _translate("MainWindow", "CFB"))
        self.keySize_en.setItemText(0, _translate("MainWindow", "128"))
        self.keySize_en.setItemText(1, _translate("MainWindow", "192"))
        self.keySize_en.setItemText(2, _translate("MainWindow", "256"))
        self.decrypt_2.setTabText(self.decrypt_2.indexOf(self.aes), _translate("MainWindow", "AES"))
        self.general.setTabText(self.general.indexOf(self.decrypt), _translate("MainWindow", "Decode"))
        self.actionExit_Alt_F4.setText(_translate("MainWindow", "Exit (Alt+F4)"))
        self.backend()

    def backend(self):
        self.convertButton_conv.clicked.connect(self.tab1)
        self.rsButton.clicked.connect(self.clear)
        self.bt_de_cea.clicked.connect(self.ceasar_de)
        self.bt_en_cea.clicked.connect(self.ceasar_en)
        self.bt_de_sub.clicked.connect(self.sub_de)
        self.bt_en_sub.clicked.connect(self.sub_en)
        self.bt_de_vig.clicked.connect(self.vig_de)
        self.bt_en_vig.clicked.connect(self.vig_en)
        self.convertButton_hash.clicked.connect(self.hash_digest)
        self.bt_gen.clicked.connect(self.geneKey)
        self.bt_en_rsa.clicked.connect(self.rsa_encrypt)
        self.bt_de_rsa.clicked.connect(self.rsa_decrypt)
        self.bt_de_aes.clicked.connect(self.aes_decrypt)
        self.bt_en_aes.clicked.connect(self.aes_encrypt)
    
    def clear(self):
        self.asciiBox.clear()
        self.decBox.clear()
        self.binBox.clear()
        self.hexBox.clear()
        self.octBox.clear()
        self.b64Box.clear()

    def tab1(self):
        a = self.asciiBox.text()
        d = self.decBox.text()
        b = self.binBox.text()
        h = self.hexBox.text()
        o = self.octBox.text()
        b64 = self.b64Box.text()
        count = 0
        if len(a):
            count+=1
        if len(d):
            count+=1
        if len(b):
            count+=1
        if len(h):
            count+=1
        if len(o):
            count+=1
        if len(b64):
            count+=1
        res =[]
        if count == 0 or count > 1:
            msg = QMessageBox()
            msg.setWindowTitle('Error')
            msg.setText("Please insert ONLY 1 line!")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec_()
            return
        if len(a):
            res = convert1.Ascii(a)
        if len(d):
            res = convert1.Decimal(d)
        if len(b):
            res = convert1.Binary(b)
        if len(h):
            res = convert1.Heximal(h)
        if len(o):
            res = convert1.Octimal(o)
        if len(b64):
            res = convert1.Base64(b64)
        if(res == 'Error'):
            msg = QMessageBox()
            msg.setWindowTitle('Error')
            msg.setText("Invalid Value!")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec_()
        else:
            self.asciiBox.setText(res[0])
            self.decBox.setText(res[1])
            self.binBox.setText(res[2])
            self.hexBox.setText(res[3])
            self.octBox.setText(res[4])
            self.b64Box.setText(res[5])
    
    def ceasar_de(self):
        text = self.ci_de_cea.toPlainText()
        shift = self.spin_de_cea.value()
        res = ceasar.decode(text, shift)
        self.pl_de_cea.setPlainText(res)

    def ceasar_en(self):
        text = self.pl_en_cea.toPlainText()
        shift = self.spin_en_cea.value()
        res = ceasar.encode(text, shift)
        self.ci_en_cea.setPlainText(res)

    def sub_de(self):
        text = self.ci_de_sub.toPlainText()
        alphabet = self.key_de_sub.text()
        alphabet = alphabet.lower() + alphabet.upper()
        res = sub.decode(text, alphabet)
        if res != 'Error':
            self.pl_de_sub.setPlainText(res)
        else:
            msg = QMessageBox()
            msg.setWindowTitle('Error')
            msg.setText("Invalid Value!")
            msg.setIcon(QMessageBox.Warning)
            x = msg.exec_()

    def sub_en(self):
        text = self.pl_en_sub.toPlainText()
        alphabet = self.key_en_sub.text()
        alphabet = alphabet.lower() + alphabet.upper()
        res = sub.encode(text, alphabet)
        if res != 'Error':
            self.ci_en_sub.setPlainText(res)
        else:
            msg = QMessageBox()
            msg.setWindowTitle('Error')
            msg.setText("Invalid Value!")
            msg.setIcon(QMessageBox.Warning)
            x = msg.exec_()
        
    def vig_de(self):
        text = self.ci_de_vig.toPlainText()
        key = self.key_de_vig.text()
        if len(key) >= 2:
            res = vigenere.decode(text, key)
            self.pl_de_vig.setPlainText(res)
        else:
            msg = QMessageBox()
            msg.setWindowTitle('Error')
            msg.setText("Please insert Key with more than 2 characters!")
            msg.setIcon(QMessageBox.Warning)
            x = msg.exec_()
        
    def vig_en(self):
        text = self.pl_en_vig.toPlainText()
        key = self.key_en_vig.text()
        if len(key) >= 2:
            res = vigenere.encode(text, key)
            self.ci_en_vig.setPlainText(res)
        else:
            msg = QMessageBox()
            msg.setWindowTitle('Error')
            msg.setText("Please insert Key with more than 2 characters!")
            msg.setIcon(QMessageBox.Warning)
            x = msg.exec_()

    def hash_digest(self):
        text = self.asciiBox_hash.text()
        if text == "":
            msg = QMessageBox()
            msg.setWindowTitle('Error')
            msg.setText("Please insert something!")
            msg.setIcon(QMessageBox.Warning)
            x = msg.exec_()
            return
        else:
            self.md5Box.setText(hashing.md5(text))
            self.ripBox.setText(hashing.rip(text))
            self.sha1Box.setText(hashing.sha_1(text))
            self.sha256Box.setText(hashing.sha_256(text))
            self.sha512Box.setText(hashing.sha_512(text))
            self.sha3Box.setText(hashing.sha_3(text))
            self.crc32Box.setText(hashing.crc32(text))

    def geneKey(self):
        size = int(self.RSAKeySize_gen.currentText())
        res = rsa_utils.genKey(size)
        self.pubKey_gen.setPlainText(res[0])
        self.priKey_gen.setPlainText(res[1])

    def rsa_encrypt(self): 
        text = self.plain_en.toPlainText()
        key = self.pubKey_en.toPlainText()
        res = rsa_utils.encryption(text, key)
        if res != 'Error':
            self.encrypt_en.setPlainText(res)
        else:
            msg = QMessageBox()
            msg.setWindowTitle('Error')
            msg.setText("Key incorrect or message corrupted!")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec_()

    def rsa_decrypt(self):
        text = self.encrypt_de.toPlainText()
        key = self.priKey_de.toPlainText()
        res = rsa_utils.decryption(text, key)
        if res != 'Error':
            self.plain_de.setPlainText(res)
        else:
            msg = QMessageBox()
            msg.setWindowTitle('Error')
            msg.setText("Key incorrect or message corrupted!")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec_()
    
    def aes_encrypt(self):
        text = self.en_en_aes.toPlainText()
        keySize = int(self.keySize_en.currentText())
        mode = self.mode_en.currentText()
        key = self.key_en_aes.text()
        if keySize/8 != len(key):
            msg = QMessageBox()
            msg.setWindowTitle('Error')
            msg.setText("Key not equal to keysize")
            msg.setInformativeText("Keysize = 128 => Length of Key = 16\nKeysize = 192 => Length of Key = 24\nKeysize = 256 => Length of Key = 32")
            msg.setIcon(QMessageBox.Warning)
            x = msg.exec_()
        else:
            a = aes.encryption(text, key, mode)
            if a == 'Error':
                msg = QMessageBox()
                msg.setWindowTitle('Error')
                msg.setText("Key incorrect or message corrupted!")
                msg.setIcon(QMessageBox.Critical)
                x = msg.exec_()
            else:
                self.pl_en_aes.setPlainText(a)

    def aes_decrypt(self):
        text = self.pl_de_aes.toPlainText()
        keySize = int(self.keySize_de.currentText())
        mode = self.mode_de.currentText()
        key = self.key_de_aes.text()
        if keySize/8 != len(key):
            msg = QMessageBox()
            msg.setWindowTitle('Error')
            msg.setText("Key not equal to keysize")
            msg.setInformativeText("Keysize = 128 => Length of Key = 16\nKeysize = 192 => Length of Key = 24\nKeysize = 256 => Length of Key = 32")
            msg.setIcon(QMessageBox.Warning)
            x = msg.exec_()
        else:
            a = aes.decryption(text, key, mode)
            if a == 'Error':
                msg = QMessageBox()
                msg.setWindowTitle('Error')
                msg.setText("Key incorrect or message corrupted!")
                msg.setIcon(QMessageBox.Critical)
                x = msg.exec_()
            else:
                self.en_de_aes.setPlainText(a)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

